from __future__ import annotations

from dataclasses import asdict
import hashlib

from docmancer.docs.application.project_docs_service import ProjectDocsService
from docmancer.docs.models import SOURCE_CLASS_PROJECT_FILE
from docmancer.docs.project import ProjectMetadataReader


def _flutter_project(tmp_path, *, fvmrc: str = "stable"):
    project = tmp_path / "app"
    project.mkdir()
    (project / ".fvmrc").write_text(fvmrc, encoding="utf-8")
    (project / "pubspec.yaml").write_text(
        """
name: app
dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  riverpod: ^2.0.0
""",
        encoding="utf-8",
    )
    (project / "pubspec.lock").write_text(
        """
packages:
  go_router:
    dependency: "direct main"
    description:
      name: go_router
      url: "https://pub.dev"
    source: hosted
    version: "14.8.1"
  riverpod:
    dependency: "direct main"
    description:
      name: riverpod
      url: "https://pub.dev"
    source: hosted
    version: "2.6.1"
sdks:
  dart: ">=3.5.0 <4.0.0"
""",
        encoding="utf-8",
    )
    return project


def _rust_project(tmp_path):
    project = tmp_path / "rust_app"
    project.mkdir()
    (project / "Cargo.toml").write_text(
        """
[package]
name = "rust_app"
version = "0.1.0"

[dependencies]
serde = "1.0"
tokio = { version = "1", features = ["rt"] }
local_crate = { path = "../local_crate" }
""",
        encoding="utf-8",
    )
    (project / "Cargo.lock").write_text(
        """
# This file is automatically @generated by Cargo.

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.48.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
""",
        encoding="utf-8",
    )
    return project


class FakeProjectFacade:
    def __init__(self):
        self.calls = []

    def _project_inspect_project_docs_impl(self, project_path):
        self.calls.append(("inspect", project_path))
        return "inspect-result"

    def _project_ingest_project_docs_impl(self, project_path, **kwargs):
        self.calls.append(("ingest", project_path, kwargs))
        return "ingest-result"

    def _project_get_project_docs_impl(self, project_path, query, **kwargs):
        self.calls.append(("get", project_path, query, kwargs))
        return "get-result"


def test_project_docs_service_delegates_inspect():
    facade = FakeProjectFacade()
    service = ProjectDocsService(facade)

    assert service.inspect_project_docs("/repo") == "inspect-result"
    assert facade.calls == [("inspect", "/repo")]


def test_project_docs_service_delegates_ingest_options():
    facade = FakeProjectFacade()
    service = ProjectDocsService(facade)

    assert service.ingest_project_docs("/repo", skip_known=False, with_vectors=False) == "ingest-result"
    assert facade.calls == [("ingest", "/repo", {"skip_known": False, "with_vectors": False})]


def test_project_docs_service_delegates_get_query_options():
    facade = FakeProjectFacade()
    service = ProjectDocsService(facade)

    assert service.get_project_docs("/repo", "architecture", tokens=100, limit=2, expand="page", module_path="packages/api", scope="module") == "get-result"
    assert facade.calls == [("get", "/repo", "architecture", {"tokens": 100, "limit": 2, "expand": "page", "module": None, "module_path": "packages/api", "scope": "module"})]


def test_project_reader_reads_pubspec_lock_versions(tmp_path):
    project = _flutter_project(tmp_path)

    metadata = ProjectMetadataReader().read(project)

    assert metadata.packages["go_router"] == "14.8.1"
    assert metadata.packages["riverpod"] == "2.6.1"


def test_project_reader_discovers_project_owned_docs(tmp_path):
    project = _flutter_project(tmp_path)
    (project / "README.md").write_text("# App", encoding="utf-8")
    (project / "ARCHITECTURE.md").write_text("# Architecture", encoding="utf-8")
    (project / "docs").mkdir()
    (project / "docs" / "testing.md").write_text("# Testing", encoding="utf-8")
    (project / "wiki").mkdir()
    (project / "wiki" / "Architecture.md").write_text("# Wiki architecture", encoding="utf-8")
    (project / "adr").mkdir()
    (project / "adr" / "0001-record.md").write_text("# ADR", encoding="utf-8")
    (project / "roadmap").mkdir()
    (project / "roadmap" / "08.md").write_text("# Roadmap", encoding="utf-8")
    (project / "lib").mkdir()
    (project / "lib" / "main.md").write_text("# Source adjacent docs should not be default", encoding="utf-8")

    metadata = ProjectMetadataReader().read(project)

    by_path = {candidate.path: candidate for candidate in metadata.docs_candidates}
    assert by_path["README.md"].reason == "root_readme"
    assert by_path["ARCHITECTURE.md"].reason == "architecture"
    assert by_path["docs/testing.md"].reason == "docs_dir"
    assert by_path["wiki/Architecture.md"].reason == "architecture"
    assert by_path["adr/0001-record.md"].reason == "adr"
    assert by_path["roadmap/08.md"].reason == "roadmap"
    assert "lib/main.md" not in by_path
    assert all(candidate.source_class == "project_file" for candidate in metadata.docs_candidates)
    assert all(candidate.doc_scope == "project" for candidate in metadata.docs_candidates)


def test_project_reader_excludes_dependency_and_build_dirs_from_docs(tmp_path):
    project = _flutter_project(tmp_path)
    (project / "README.md").write_text("# App", encoding="utf-8")
    for directory in ("node_modules", ".venv", "build", ".git"):
        nested = project / directory / "docs"
        nested.mkdir(parents=True)
        (nested / "README.md").write_text("# Hidden", encoding="utf-8")

    metadata = ProjectMetadataReader().read(project)

    paths = {candidate.path for candidate in metadata.docs_candidates}
    assert paths == {"README.md"}


def test_missing_project_path_returns_single_warning(tmp_path):
    missing = tmp_path / "missing"

    metadata = ProjectMetadataReader().read(missing)

    assert metadata.warnings == [f"Project path not found: {missing.resolve()}"]
    assert metadata.docs_candidates == []
    assert metadata.packages == {}


def test_project_reader_discovers_module_owned_docs(tmp_path):
    project = _flutter_project(tmp_path)
    (project / "README.md").write_text("# App", encoding="utf-8")
    backend_docs = project / "packages" / "backend" / "docs"
    backend_docs.mkdir(parents=True)
    (project / "packages" / "backend" / "README.md").write_text("# Backend", encoding="utf-8")
    (backend_docs / "architecture.md").write_text("# Backend architecture", encoding="utf-8")
    web = project / "apps" / "web"
    web.mkdir(parents=True)
    (web / "README.md").write_text("# Web", encoding="utf-8")
    auth_docs = project / "services" / "auth" / "docs"
    auth_docs.mkdir(parents=True)
    (auth_docs / "token-lifecycle.md").write_text("# Tokens", encoding="utf-8")
    ignored_docs = project / "packages" / "ignored" / "src"
    ignored_docs.mkdir(parents=True)
    (ignored_docs / "notes.md").write_text("# Not module docs", encoding="utf-8")

    metadata = ProjectMetadataReader().read(project)

    by_path = {candidate.path: candidate for candidate in metadata.docs_candidates}
    assert by_path["README.md"].doc_scope == "project"
    assert by_path["packages/backend/README.md"].doc_scope == "module"
    assert by_path["packages/backend/README.md"].module_id == "packages/backend"
    assert by_path["packages/backend/README.md"].module_name == "backend"
    assert by_path["packages/backend/README.md"].module_path == "packages/backend"
    assert by_path["packages/backend/README.md"].module_type == "package"
    assert by_path["packages/backend/docs/architecture.md"].reason == "architecture"
    assert by_path["apps/web/README.md"].module_type == "app"
    assert by_path["services/auth/docs/token-lifecycle.md"].module_type == "service"
    assert "packages/ignored/src/notes.md" not in by_path


def test_project_reader_discovers_flutter_lib_modules_and_features_docs(tmp_path):
    project = _flutter_project(tmp_path)
    (project / "README.md").write_text("# App", encoding="utf-8")
    orders_docs = project / "lib" / "modules" / "orders" / "docs"
    orders_docs.mkdir(parents=True)
    (project / "lib" / "modules" / "orders" / "README.md").write_text("# Orders", encoding="utf-8")
    (orders_docs / "architecture.md").write_text("# Orders architecture", encoding="utf-8")
    auth_docs = project / "lib" / "features" / "auth" / "docs"
    auth_docs.mkdir(parents=True)
    (auth_docs / "flow.md").write_text("# Auth flow", encoding="utf-8")
    misc = project / "lib" / "utils"
    misc.mkdir(parents=True)
    (misc / "notes.md").write_text("# Not feature docs", encoding="utf-8")

    metadata = ProjectMetadataReader().read(project)

    by_path = {candidate.path: candidate for candidate in metadata.docs_candidates}
    assert by_path["lib/modules/orders/README.md"].doc_scope == "module"
    assert by_path["lib/modules/orders/README.md"].module_id == "lib/modules/orders"
    assert by_path["lib/modules/orders/README.md"].module_type == "module"
    assert by_path["lib/modules/orders/docs/architecture.md"].reason == "architecture"
    assert by_path["lib/features/auth/docs/flow.md"].module_type == "feature"
    assert "lib/utils/notes.md" not in by_path


def test_project_docs_candidate_has_stable_serializable_shape_and_freshness(tmp_path):
    project = _flutter_project(tmp_path)
    body = "# App\n"
    (project / "README.md").write_text(body, encoding="utf-8")

    metadata = ProjectMetadataReader().read(project)

    candidate = next(item for item in metadata.docs_candidates if item.path == "README.md")
    assert candidate.source_class == SOURCE_CLASS_PROJECT_FILE
    assert candidate.size_bytes == len(body.encode("utf-8"))
    assert candidate.mtime_ns is not None
    assert candidate.content_hash == f"sha256:{hashlib.sha256(body.encode('utf-8')).hexdigest()}"
    assert asdict(candidate) == {
        "path": "README.md",
        "source_class": "project_file",
        "reason": "root_readme",
        "size_bytes": len(body.encode("utf-8")),
        "mtime_ns": candidate.mtime_ns,
        "content_hash": candidate.content_hash,
        "doc_scope": "project",
        "module_id": None,
        "module_name": None,
        "module_path": None,
        "module_type": None,
    }


def test_project_reader_emits_normalized_pub_dependency_observations(tmp_path):
    project = _flutter_project(tmp_path)

    metadata = ProjectMetadataReader().read(project)

    go_router = next(item for item in metadata.dependencies if item.ecosystem == "pub" and item.package_name == "go_router" and item.resolved_version)
    assert go_router.dependency_group == "dependencies"
    assert go_router.specifier_kind == "exact"
    assert go_router.resolved_version == "14.8.1"
    assert go_router.version_source == "lockfile_exact"
    assert go_router.source_kind == "registry"


def test_project_reader_reads_cargo_lock_versions(tmp_path):
    project = _rust_project(tmp_path)

    metadata = ProjectMetadataReader().read(project)

    assert metadata.packages["rust:serde"] == "1.0.228"
    assert "rust" in metadata.detected_ecosystems
    serde = next(item for item in metadata.dependencies if item.ecosystem == "rust" and item.package_name == "serde")
    assert serde.specifier_raw == "1.0"
    assert serde.resolved_version == "1.0.228"
    assert serde.version_source == "lockfile_exact"


def test_project_reader_preserves_go_router_underscore(tmp_path):
    project = _flutter_project(tmp_path)

    metadata = ProjectMetadataReader().read(project)

    assert "go_router" in metadata.packages
    assert "go-router" not in metadata.packages


def test_project_reader_reads_fvmrc(tmp_path):
    project = _flutter_project(tmp_path, fvmrc='{"flutter": "3.24.5", "channel": "stable"}')

    metadata = ProjectMetadataReader().read(project)

    assert metadata.flutter_version == "3.24.5"
    assert metadata.flutter_channel == "stable"
